version: '3'
services:
  portal:
    image: liferay/portal:7.4.0-dxp  # Update to use official Liferay 7.4 DXP image
    networks:
      - lfrnet
    ports:
      - "8080:8080"  # Expose port 8080 for HTTP
      - "8009:8009"  # Optional: AJP connector if needed
    environment:
      LIFERAY_HOME: /opt/liferay
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      LIFERAY_TOMCAT_PASSWORD: root  # Optional: Set Tomcat password (default is 'root')
    volumes:
      - liferay-document-library:/opt/liferay/data/document_library
      - ${LIFERAY_BUNDLE_DIR}/osgi/configs:/opt/liferay/osgi/configs
      - ${LIFERAY_BUNDLE_DIR}/deploy:/opt/liferay/deploy
      - ${LIFERAY_BUNDLE_DIR}/osgi/marketplace:/opt/liferay/osgi/marketplace
      - ${LIFERAY_BUNDLE_DIR}/osgi/modules:/opt/liferay/osgi/modules
      - ${LIFERAY_BUNDLE_DIR}/portal-ext.properties:/opt/liferay/portal-ext.properties
      - ${LIFERAY_BUNDLE_DIR}/osgi/war:/opt/liferay/osgi/war
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0  # Using the official MySQL 8.0 image
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - lfrnet
    ports:
      - "3306:3306"  # Expose MySQL port
    volumes:
      - db-data:/var/lib/mysql
    restart: always

  # Optional: Elasticsearch service if you want it
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0  # Compatible Elasticsearch version
    environment:
      - discovery.type=single-node
    networks:
      - lfrnet
    ports:
      - "9200:9200"  # Expose Elasticsearch port
    volumes:
      - elastisearch-data:/usr/share/elasticsearch/data
    restart: always

networks:
  lfrnet:

volumes:
  liferay-document-library:
  db-data:
  elastisearch-data:
